### PR TITLE
Make sure to alwayse call the membership validation in mozaik_members…

### PR DESCRIPTION
**Pull request by RobinetDenisAcsone**
…hip_payment to correctly mark the membership as paid if needed

### CODE REVIEW

**Comment by marielejeune** [comment]
@RobinetDenisAcsone is there any reason for _validate_request_membership and _validate_request_membership_with_checks to be decorated with api.model and take the MR as a parameter?

**Comment by RobinetDenisAcsone** [comment]
@marielejeune I don't think, it could be an @api.mulit with self.ensure_one()

**Comment by marielejeune** [comment]
@RobinetDenisAcsone in v14 api.multi is deprecated, so I'll just modify the methods and call self.ensure_one()

**Comment by marielejeune** [comment]
Modification done here: https://github.com/mozaik-association/mozaik/pull/683

**Pull request merged**
